package com.example.quokka_app.ui.newpatientprofile

data class NewPatienProfileDataClass(
    val First_Name: String,
    val Middle_Name: String,
    val Last_Name: String,
    val Date_Of_Birth: String,
    val lastmenstcycle: Boolean,
    val lastmenstcycledate: String,
    val motherbirthdefect: Boolean,
    val motherbirthdefecttype: String,
    val firstpregnancy: Boolean,
    val numpregn: String,
    val livingchildren: String,
    val lowbirthweight: String,
    val stillborns: String,
    val miscarriages: String,
    val csections: String,
    val postpartumhemorrhages: String,
    val preginfections: String,
    val highBPpregn: String,
    val othermedhist: String,
    val alcoholconsump: Boolean,
    val drinksperweek: String,
    val smoking: Boolean,
    val smokesperweek: String,
    val drugs: Boolean,
    val drugtypes: String,
    val exercise: String,
)
