package com.example.quokka_app.ui.newpatientprofile

data class NewPatienProfileDataClass(
    val First_Name: String,
    val Middle_Name: String,
    val Last_Name: String,
    val Date_Of_Birth: String,
    val Mothers_Village: String,
    val lastmenstcycle: String?,
    val lastmenstcycledate: String,
    val Mothers_Phone_Number: String,
    val Fathers_First_Name: String,
    val Fathers_Middle_Name: String,
    val Fathers_Last_Name: String,
    val Fathers_Village: String,
    val Fathers_Phone_Number: String,
    val FCHW_First_Name: String,
    val FCHW_Last_Name: String,
    val FCHW_Phone_Number: String,
    val motherbirthdefect: String?,
    val motherbirthdefecttype: String,
    val firstpregnancy: String?,
    val numpregn: String,
    val livingchildren: String,
    val lowbirthweight: String,
    val stillborns: String,
    val miscarriages: String,
    val csections: String,
    val postpartumhemorrhages: String,
    val preginfections: String,
    val highBPpregn: String,
    val pregseizures: String?,
    val othermedhist: String,
    val alcoholconsump: String?,
    val smoking: String?,
    val drugs: String?,
    val drugtypes: String,
)
